# TODO improve artifacts sharing between the jobs, keep track of the following issues:
# - https://github.com/travis-ci/travis-ci/issues/7590
# - https://travis-ci.community/t/using-unified-cache-control-cache-identity/1531

branches: { only: [ master ] }
node_js: 15
language: node_js
cache: false
env:
  - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
anchors:
  macos-common: &macos-common
    os: osx
    osx_image: xcode9.4
  macos-build-app: &macos-build-app
    script: ./scripts/ci/travis/build-osx.sh
    after_failure:
      - tar -cvf e2e-logs.tar ./output/e2e
      - yarn scripts/transfer upload e2e-logs.tar
install:
  - npx envinfo
  - yarn install --pure-lockfile
  - yarn cache clean
notifications: { email: { on_success: never, on_failure: change } }
jobs:
  include:
    - stage: "build proton clients"
      <<: *macos-common
      cache: { yarn: false, npm: false, directories: [ "./output/git/backup", "./app/assets/db-search-monaco-editor" ] }
      script: ./scripts/ci/prepare-webclients.sh
      workspaces: { create: { name: "macos-webclients-artifact", paths: [ "./output/git/backup", "./app/assets/db-search-monaco-editor" ] } }
    - stage: "build app package"
      <<: *macos-common
      <<: *macos-build-app
      osx_image: xcode9.4
      workspaces: { use: [ "macos-webclients-artifact" ] }
