# TODO improve artifacts sharing between the jobs, keep track of the following issues:
# - https://github.com/travis-ci/travis-ci/issues/7590
# - https://travis-ci.community/t/using-unified-cache-control-cache-identity/1531

branches:
  only:
    - master

node_js: 12
language: node_js

embedding-prepare-webclients: &embedding-prepare-webclients-anchor
  cache:
    yarn: false
    npm: false
    directories:
      - output/git/proton-calendar
      - output/git/proton-contacts
      - output/git/proton-mail-settings
  workspaces:
    create:
      name: 'webclients-artifact'
      paths:
        - output/git
  env:
    - ELECTRON_MAIL_PREPARE_WEBCLIENTS_REPOS_ONLY="proton-mail-settings;proton-contacts;proton-calendar"
  script: ./scripts/ci/prepare-webclients.sh

embedding-linux-common: &embedding-linux-common-anchor
  os: linux
  dist: bionic
  env:
    # needed for: native modules compiling
    - CC=gcc-7 CXX=g++-7
  addons:
    apt:
      packages:
        # needed for: native modules compiling
        - g++-7
        # needed for: compiling "desktop-idle" native module
        - libxss-dev
        # needed for: keychain initialization and compiling "node-keytar" native module
        - gnome-keyring
        - libgnome-keyring-dev
        - libsecret-1-dev
        # needed for: keychain access testing before running e2e tests (see "scripts/ci/add-secret-service-item-assert.py")
        - python3-secretstorage
        # needed for: tweaking snap package ("unsquashfs" binary)
        - squashfs-tools

embedding-macos-common: &embedding-macos-common-anchor
  os: osx

embedding-build-app-common: &embedding-build-app-common-anchor
  cache:
    yarn: false
    npm: false
    directories:
      - output/git
  workspaces:
    use:
      - 'webclients-artifact'
  after_failure:
    - tar -cvf e2e-logs.tar ./output/e2e
    - yarn scripts/transfer upload e2e-logs.tar

before_install:
  - | # installing the most recent yarn version
    curl -o- -L https://yarnpkg.com/install.sh | bash;
    export PATH="$HOME/.yarn/bin:$PATH";
install:
  - node --version
  - npm --version
  - yarn --version
  - npx envinfo
  - yarn install --pure-lockfile
notifications:
  email:
    on_success: never
    on_failure: change

embedding-build-app-macos: &embedding-build-app-macos-anchor
  env:
    - ARTIFACT_NAME_POSTFIX="-$TRAVIS_OSX_IMAGE"
  script: ./scripts/ci/travis/build-osx.sh

jobs:
  include:
    # pre-build some web clients to workaround the issue of travis dropping long-running jobs on free plan
    - stage: 'Build web clients (settings/contacts/calendar only)'
      <<: *embedding-linux-common-anchor
      <<: *embedding-prepare-webclients-anchor
    - stage: 'Build web clients (settings/contacts/calendar only)'
      <<: *embedding-macos-common-anchor
      <<: *embedding-prepare-webclients-anchor
      osx_image: xcode9.4
    - stage: 'Build web clients (settings/contacts/calendar only)'
      <<: *embedding-macos-common-anchor
      <<: *embedding-prepare-webclients-anchor
      osx_image: xcode10.3
    - stage: 'Build web clients (settings/contacts/calendar only)'
      <<: *embedding-macos-common-anchor
      <<: *embedding-prepare-webclients-anchor
      osx_image: xcode11.3
    - stage: 'Build App'
      <<: *embedding-linux-common-anchor
      <<: *embedding-build-app-common-anchor
      sudo: required
      services:
        - docker
        # needed for: running e2e tests
        - xvfb
      before_script:
        - | # init dbus
          NO_AT_BRIDGE=1;
          eval $(dbus-launch --sh-syntax);
        # TODO get back keyring initialization then enable respective e2e test case (see "src/e2e/index.spec.ts")
        #- | # init keychain
        #  eval $(echo -n "" | /usr/bin/gnome-keyring-daemon --login);
        #  eval $(/usr/bin/gnome-keyring-daemon --components=secrets --start);
        #  python3 ./scripts/ci/add-secret-service-item-assert.py;
      script: ./scripts/ci/travis/build-linux.sh
    # see travis macOS images list at https://docs.travis-ci.com/user/reference/osx/
    - stage: 'Build app'
      <<: *embedding-macos-common-anchor
      <<: *embedding-build-app-common-anchor
      <<: *embedding-build-app-macos-anchor
      osx_image: xcode9.4
    - stage: 'Build app'
      <<: *embedding-macos-common-anchor
      <<: *embedding-build-app-common-anchor
      <<: *embedding-build-app-macos-anchor
      osx_image: xcode10.3
    - stage: 'Build app'
      <<: *embedding-macos-common-anchor
      <<: *embedding-build-app-common-anchor
      <<: *embedding-build-app-macos-anchor
      osx_image: xcode11.3
