# http://www.appveyor.com/docs/appveyor-yml

# TODO share artifacts properly, track the following issues resolving:
# - https://github.com/appveyor/ci/issues/2438
# - https://github.com/appveyor/ci/issues/1623

branches:
  only:
    - master
skip_tags: true
image:
  # WARN "image" items ordering matters
  - 'Ubuntu1804'
  - 'Visual Studio 2017'
platform:
  - x64
build: off
test: off
matrix:
  fast_finish: true
environment:
  nodejs_version: 11.14.0
  nodejs_arch: x64
  APP_LINUX_JOB_NAME_PATTERN: 'image: Ubuntu1804'
  APP_GITHUB_ARTIFACT_WEBCLIENTS: appveyor-%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_COMMIT%-app-webclients.zip
for:
  - matrix:
      only:
        - image: 'Ubuntu1804'
    install:
      - sudo apt-get --yes install gnome-keyring libgnome-keyring-dev libsecret-1-dev nasm
      - cmd: powershell Install-Product node $env:nodejs_version $env:nodejs_arch
      - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
      - export PATH="$HOME/.yarn/bin:$PATH"
      - nvm install $nodejs_version
      - npm install --global yarn
      - node --version
      - npm --version
      - yarn --version
      - yarn install --pure-lockfile
    build_script:
      - yarn assets:webclient:tutanota
      - yarn assets:webclient:protonmail
      - zip -r $APP_GITHUB_ARTIFACT_WEBCLIENTS ./app
      - ls
      - yarn github-artifact:upload $APP_GITHUB_ARTIFACT_WEBCLIENTS
  - matrix:
      only:
        - image: 'Visual Studio 2017'
    install:
      - ps: Install-Product node $env:nodejs_version $env:nodejs_arch
      - ps: | # installing the most recent yarn version
          (New-Object Net.WebClient).DownloadFile("https://yarnpkg.com/latest.msi", "$env:temp\yarn.msi")
          cmd /c start /wait msiexec.exe /i $env:temp\yarn.msi /quiet /qn /norestart
      - SET CI=true
      - npm install --global yarn
      - set PATH=%PATH%;C:\.yarn\bin
      - node --version
      - npm --version
      - yarn --version
      - yarn install --pure-lockfile --mutex file
    build_script:
      - ps: |
          yarn github-artifact:download $env:APP_GITHUB_ARTIFACT_WEBCLIENTS
          7z.exe x $env:APP_GITHUB_ARTIFACT_WEBCLIENTS
      - yarn app:dist
      - yarn test:e2e
      - yarn electron-builder:publish:x64
      - yarn print-dist-packages-hashes
    on_finish:
      - ps: Get-Process
      - SET APP_GITHUB_ARTIFACT_LOG=appveyor-%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_COMMIT%-%APPVEYOR_JOB_NUMBER%-log.zip
      - 7z a %APP_GITHUB_ARTIFACT_LOG% output\e2e\*
      - dir
      - appveyor PushArtifact %APP_GITHUB_ARTIFACT_LOG%
      - yarn github-artifact:upload %APP_GITHUB_ARTIFACT_LOG%
