# http://www.appveyor.com/docs/appveyor-yml

branches:
  only:
    - master
skip_tags: true
os: unstable
environment:
  matrix:
    - nodejs_version: 8
platform:
  - x64
cache:
  - "%LOCALAPPDATA%/Yarn"
  - "%USERPROFILE%/.electron"
  - "%USERPROFILE%/.electron-builder"
test: off
install:
  - ps: Install-Product node $env:node_version
  - SET CI=true
  - yarn install --mutex file
build_script:
  - node --version
  - yarn --version
  - yarn run app:dist
  - yarn run electron-builder:release:x64
